"""update products to have product_name

Revision ID: 87de3deb7861
Revises: a8a85a9dde0f
Create Date: 2026-09-03 16:49:20.662106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87de3deb7861'
down_revision: Union[str, Sequence[str], None] = 'a8a85a9dde0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_name', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'product_name')
    # ### end Alembic commands ###
